
test:
  stage: test
  script:
    - sbt test

deploy:
  stage: deploy
  only: 
    - master
    - 0.5
  script:
    - sbt +publish
    - sbt bootstrap
    - cp bin/vizier /var/www/maven_repo/info/vizierdb/